# Generated by Django 5.0.6 on 2024-06-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_user_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(blank=True, default='Sin descripción', max_length=5000, null=True),
        ),
    ]
